general_responsibilities:
  - title: Glass Damage Repair/Replacement Program
    description: Review all glass damage and determine appropriate repair or replacement actions.
    owner: Dirk Steele
  - title: PM Records Management
    description: Oversee onsite and local market PM Records Management to ensure compliance with regulatory standards
    owner: Dirk Steele
  - title: Lost Keys Replacement Program
    description: Oversee lost keys replacement program including vendor relationships and service level agreements
    owner: Dirk Steele
  - title: Repair Order Closeout Processing
    description: Manage repair order closeout processing to ensure timely completion and accurate documentation
    owner: Dirk Steele
  - title: Supply Management
    description: Monitor and Report on Airport Oil Levels
    owner: Dirk Steele
